# This configuration tells Netlify how to build and deploy the Python-based demo site.

[build]
  # 1. Install project dependencies: This command installs the main 'project-resonance'
  #    package in editable mode, along with the extras needed for the demos.
  #    You should define a 'demos' extra in your setup.py or pyproject.toml.
  command = "pip install --upgrade pip && pip install -e .[demos]"
  
  # 2. Serverless Functions: This is where Netlify will find the Python handler for the site.
  functions = "netlify/functions/"
  
  # 3. Static Assets: This directory contains static files (CSS, JS, images) that
  #    Netlify can serve directly for better performance.
  publish = "resonance_demos/static/"

[build.environment]
  # Specify the Python version for the build environment.
  PYTHON_VERSION = "3.10"

# This rule is crucial. It directs all incoming traffic (e.g., /, /about, /demo/...)
# to the serverless function that runs the FastAPI app. Netlify is smart enough
# to serve any matching static files from the 'publish' directory first.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200