# This is the definitive, production-ready configuration file for Netlify.

[build]
  # The command to build the entire project.
  command = "pip install --upgrade pip && pip install -e .[benchmark,demos]"
  
  # The directory containing the serverless function.
  functions = "netlify/functions/"
  
  # --- DEFINITIVE FIX ---
  # The publish directory should ONLY contain assets that are served directly.
  # All our HTML pages are dynamic templates, so only 'static' is needed here.
  publish = "resonance_demos/static/"

# --- DEFINITIVE FIX ---
# This is the magic rule. It tells Netlify to route ALL incoming requests
# (like /, /about, /demo/market, /api/balance) to our Python serverless function.
# Netlify's engine is smart enough to check for a static file in the 'publish'
# directory first (e.g., /css/style.css) before applying this rule.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200