# This is the master configuration file for Netlify.
# It tells Netlify how to build and deploy your project.

[build]
  # The command to build your entire project. This will:
  # 1. Install all Python dependencies from both requirements files.
  # 2. Compile the C++ core for the phicomp library.
  # 3. Install the project-resonance package itself.
  command = "pip install --upgrade pip && pip install -r resonance_demos/requirements.txt && pip install ."
  
  # The directory containing the serverless function.
  functions = "netlify/functions/"
  
  # The directory containing the static web files to be published.
  publish = "resonance_demos/"

# This is the magic rule. It tells Netlify to route all requests
# that are not for a static file (like CSS or JS) to our Python serverless function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200